export const BRAND = {
  name: "GERMANTEES",
  tagline: "NO COMPROMISE.",
  mantra: "DEFINE. TEST. INSPECT. IMPROVE. REPEAT.",
  philosophy: "Inspired by German precision. Made for Indian life.",
} as const;

export const NAV_LINKS = [
  { label: "Home", href: "/" },
  { label: "Kids", href: "/kids" },
  { label: "Baby", href: "/baby" },
  { label: "Family", href: "/family" },
  { label: "Birthday", href: "/birthday" },
  { label: "Festivals", href: "/festivals" },
  { label: "Create Your Own", href: "/customize" },
  { label: "Design Studio", href: "/design-studio" },
] as const;

export const FOOTER_LINKS = {
  shop: [
    { label: "Kids", href: "/kids" },
    { label: "Baby", href: "/baby" },
    { label: "Family", href: "/family" },
    { label: "Birthday", href: "/birthday" },
    { label: "Customize", href: "/customize" },
    { label: "Design Studio", href: "/design-studio" },
  ],
  brand: [
    { label: "Our Philosophy", href: "/our-philosophy" },
    { label: "Germantees Standard", href: "/germantees-standard" },
    { label: "Fabrics", href: "/fabrics" },
    { label: "Quality", href: "/quality" },
    { label: "About", href: "/about" },
  ],
  help: [
    { label: "Size Guide", href: "/size-guide" },
    { label: "Care Guide", href: "/care-guide" },
    { label: "Shipping", href: "/shipping" },
    { label: "Returns", href: "/returns" },
    { label: "Track Order", href: "/track-order" },
    { label: "Contact", href: "/contact" },
  ],
  social: [
    { label: "Instagram", href: "https://instagram.com/germantees" },
    { label: "Facebook", href: "https://facebook.com/germantees" },
    { label: "WhatsApp", href: "https://wa.me/919999999999" },
  ],
} as const;

export const QUALITY_PILLARS = [
  {
    number: "01",
    title: "Chemical & Product Safety",
    description: "Defined and verified safety parameters based on applicable requirements.",
  },
  {
    number: "02",
    title: "Fabric Quality",
    description: "Composition, GSM, shrinkage, colour fastness — specified and measured.",
  },
  {
    number: "03",
    title: "Garment Construction",
    description: "Stitching, seams, collar, hems — inspected for every production run.",
  },
  {
    number: "04",
    title: "Printing",
    description: "Appearance, adhesion, wash durability — controlled and verified.",
  },
  {
    number: "05",
    title: "Final QC",
    description: "Every garment passes a repeatable inspection before it reaches you.",
  },
] as const;

export const QUALITY_PROMISE = [
  { label: "DEFINED QUALITY", icon: "ruler" },
  { label: "TESTED MATERIALS", icon: "flask-conical" },
  { label: "INSPECTED GARMENTS", icon: "search-check" },
  { label: "PERSONALIZED WITH CARE", icon: "heart-handshake" },
] as const;

export const OCCASIONS = [
  { title: "First Birthday", slug: "first-birthday", image: "/images/occasions/first-birthday.jpg" },
  { title: "Birthday", slug: "birthday", image: "/images/occasions/birthday.jpg" },
  { title: "Mom & Child", slug: "mom-child", image: "/images/occasions/mom-child.jpg" },
  { title: "Dad & Child", slug: "dad-child", image: "/images/occasions/dad-child.jpg" },
  { title: "Siblings", slug: "siblings", image: "/images/occasions/siblings.jpg" },
  { title: "Family Vacation", slug: "family-vacation", image: "/images/occasions/family-vacation.jpg" },
  { title: "Festivals", slug: "festivals", image: "/images/occasions/festivals.jpg" },
  { title: "Photoshoots", slug: "photoshoots", image: "/images/occasions/photoshoots.jpg" },
] as const;

export const TSHIRT_COLORS = [
  { name: "White", hex: "#FFFFFF" },
  { name: "Black", hex: "#111827" },
  { name: "Navy", hex: "#1E3A5F" },
  { name: "Red", hex: "#DC2626" },
  { name: "Yellow", hex: "#FACC15" },
  { name: "Pink", hex: "#F472B6" },
  { name: "Green", hex: "#16A34A" },
  { name: "Blue", hex: "#3B82F6" },
] as const;

export const SIZE_CHART = {
  boy: [
    { label: "2-3Y", chest: 24, length: 15 },
    { label: "3-4Y", chest: 25, length: 16 },
    { label: "4-5Y", chest: 26, length: 17 },
    { label: "5-6Y", chest: 27, length: 18 },
    { label: "6-7Y", chest: 28, length: 19 },
    { label: "7-8Y", chest: 29, length: 20 },
    { label: "8-10Y", chest: 30, length: 21 },
    { label: "10-12Y", chest: 32, length: 23 },
    { label: "12-14Y", chest: 34, length: 25 },
  ],
  girl: [
    { label: "2-3Y", chest: 24, length: 15 },
    { label: "3-4Y", chest: 25, length: 16 },
    { label: "4-5Y", chest: 26, length: 17 },
    { label: "5-6Y", chest: 27, length: 18 },
    { label: "6-7Y", chest: 28, length: 19 },
    { label: "7-8Y", chest: 29, length: 20 },
    { label: "8-10Y", chest: 30, length: 21 },
    { label: "10-12Y", chest: 32, length: 23 },
    { label: "12-14Y", chest: 34, length: 25 },
  ],
  men: [
    { label: "S", chest: 38, length: 27 },
    { label: "M", chest: 40, length: 28 },
    { label: "L", chest: 42, length: 29 },
    { label: "XL", chest: 44, length: 30 },
    { label: "XXL", chest: 46, length: 31 },
  ],
  women: [
    { label: "XS", chest: 32, length: 24 },
    { label: "S", chest: 34, length: 25 },
    { label: "M", chest: 36, length: 26 },
    { label: "L", chest: 38, length: 27 },
    { label: "XL", chest: 40, length: 28 },
  ],
} as const;

export const MOCK_PRODUCTS = [
  {
    id: "1",
    name: "Birthday Boy Tee",
    slug: "birthday-boy-tee",
    description: "Premium cotton personalized birthday tee for your little one.",
    price: 699,
    originalPrice: 999,
    images: ["/images/products/birthday-boy-1.jpg"],
    colors: ["White", "Navy", "Black"],
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y", "6-7Y", "7-8Y"],
    category: "birthday",
    rating: 4.8,
    reviewCount: 124,
    personalizationEnabled: true,
    qualityTag: "Premium cotton | Personalized",
    fabricSpec: "Sample specification",
  },
  {
    id: "2",
    name: "Family Vacation Combo",
    slug: "family-vacation-combo",
    description: "Matching family tees for your next vacation adventure.",
    price: 1999,
    originalPrice: 2999,
    images: ["/images/products/family-combo-1.jpg"],
    colors: ["White", "Navy"],
    sizes: ["Family Pack"],
    category: "family",
    rating: 4.9,
    reviewCount: 87,
    personalizationEnabled: true,
    qualityTag: "Premium cotton | Family set",
    fabricSpec: "Sample specification",
  },
  {
    id: "3",
    name: "Little Princess Tee",
    slug: "little-princess-tee",
    description: "Elegant personalized tee for your little princess.",
    price: 649,
    originalPrice: 899,
    images: ["/images/products/princess-1.jpg"],
    colors: ["Pink", "White", "Yellow"],
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y"],
    category: "kids",
    rating: 4.7,
    reviewCount: 203,
    personalizationEnabled: true,
    qualityTag: "Premium cotton | Personalized",
    fabricSpec: "Sample specification",
  },
  {
    id: "4",
    name: "First Birthday Special",
    slug: "first-birthday-special",
    description: "Make the first birthday unforgettable with a personalized tee.",
    price: 799,
    originalPrice: 1199,
    images: ["/images/products/first-birthday-1.jpg"],
    colors: ["White", "Blue", "Pink"],
    sizes: ["6-12M", "1-2Y", "2-3Y"],
    category: "birthday",
    rating: 4.9,
    reviewCount: 312,
    personalizationEnabled: true,
    qualityTag: "Premium cotton | First birthday",
    fabricSpec: "Sample specification",
  },
  {
    id: "5",
    name: "Mom & Son Duo",
    slug: "mom-son-duo",
    description: "Matching tees celebrating the mother-son bond.",
    price: 1299,
    originalPrice: 1799,
    images: ["/images/products/mom-son-1.jpg"],
    colors: ["White", "Navy", "Black"],
    sizes: ["Duo Pack"],
    category: "family",
    rating: 4.8,
    reviewCount: 156,
    personalizationEnabled: true,
    qualityTag: "Premium cotton | Duo set",
    fabricSpec: "Sample specification",
  },
  {
    id: "6",
    name: "Dad & Daughter Tee Set",
    slug: "dad-daughter-set",
    description: "Adorable matching tees for dad and his little girl.",
    price: 1299,
    originalPrice: 1799,
    images: ["/images/products/dad-daughter-1.jpg"],
    colors: ["Navy", "White", "Black"],
    sizes: ["Duo Pack"],
    category: "family",
    rating: 4.7,
    reviewCount: 98,
    personalizationEnabled: true,
    qualityTag: "Premium cotton | Duo set",
    fabricSpec: "Sample specification",
  },
  {
    id: "7",
    name: "Festival Special Tee",
    slug: "festival-special-tee",
    description: "Celebrate festivals in style with personalized tees.",
    price: 749,
    originalPrice: 1099,
    images: ["/images/products/festival-1.jpg"],
    colors: ["White", "Red", "Yellow", "Green"],
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y", "6-7Y", "7-8Y"],
    category: "festivals",
    rating: 4.6,
    reviewCount: 67,
    personalizationEnabled: true,
    qualityTag: "Premium cotton | Festival edition",
    fabricSpec: "Sample specification",
  },
  {
    id: "8",
    name: "Sibling Squad Tees",
    slug: "sibling-squad-tees",
    description: "Fun matching tees for brothers, sisters, and sibling duos.",
    price: 1199,
    originalPrice: 1599,
    images: ["/images/products/siblings-1.jpg"],
    colors: ["White", "Navy", "Black"],
    sizes: ["Sibling Pack"],
    category: "family",
    rating: 4.8,
    reviewCount: 145,
    personalizationEnabled: true,
    qualityTag: "Premium cotton | Sibling set",
    fabricSpec: "Sample specification",
  },
] as const;

export type Product = (typeof MOCK_PRODUCTS)[number];
